# NumPy

In [2]:
import numpy as np

1. array with 8x4x4 dimensions

In [10]:
matrix1 = np.zeros((8,4,4))

2. change data type to integer

In [21]:
matrix1.dtype
matrix1 = np.zeros(shape=(8,4,4), dtype=int)
matrix1.dtype

dtype('int32')

3. create an one dimensional array

In [31]:
cars = ['audi', 'bmw', 'vw']
cars_array = np.array(cars)
cars_array

array(['audi', 'bmw', 'vw'], dtype='<U4')

4. create multi-dimensional array with 3 dimensions

In [29]:
grades = [[[1,2,3,4,5,6], [1,2,3,4,5,6]],[[1,2,3,4,5,6], [1,2,3,4,5,6]]]
np.array(grades)

array([[[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]],

       [[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]]])

5. shape + ndim of array cars

In [32]:
cars_array.shape, cars_array.ndim

((3,), 1)

6. one-dimensional ndarray

In [37]:
np.ndarray((2))

array([-1.35685759e+82, -7.94734890e+31])

7. two-dimensional ndarray

In [38]:
np.ndarray((2,2))

array([[2.12199579e-314, 0.00000000e+000],
       [2.07507571e-321, 7.19364863e-312]])

8. three-dimenaional ndarray

In [49]:
np.ndarray((2,2,2))
array_reshape = np.array([1,2,3,4,5,6,7,8,9])

array_reshape.reshape((1,3,3))

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

9. convert list to multi-dimensional array

In [57]:
list1 = ['item1', 'item2', 'item3']
np.asarray(list1)

array(['item1', 'item2', 'item3'], dtype='<U5')

10. generate a 2x4 array with random integers from 0 to 4

In [98]:
# array_randint = np.full((2,4), fill_value=np.random.randint(0,4), dtype=int)
array_randint = np.random.randint(5, size=(2,4))
array_randint

array([[1, 3, 0, 3],
       [0, 0, 2, 2]])

11. change the array's dimensions to 4x2

In [22]:
array_randint.reshape(4,2)

NameError: name 'array_randint' is not defined

>transpose is the preferred method

In [101]:
np.transpose(array_randint)

array([[1, 0],
       [3, 0],
       [0, 2],
       [3, 2]])

#### help functions

<code>
    help(np.array)
    np.info(np.array)
</code>

## NumPy arithmetic operations 

In [ ]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

- multiplication

In [ ]:
v1 * v2, v1 * 2.5

- division 

In [ ]:
v1 / v2, v1 / 2

- addition / multiplication

In [ ]:
print(f'Add: {v1 + v2}')
print(f'Sub: {v1 - v2}')

- raise to power

In [ ]:
v2 ** 2

- square root

In [20]:
v2 ** 0.5, np.sqrt(v2)

(array([2.        , 2.23606798, 2.44948974]),
 array([2.        , 2.23606798, 2.44948974]))

## NumPy descriptive statistics

- sum

In [16]:
np.sum(v2, dtype=np.int32) # default: float64

15

- average

In [ ]:
np.average(v2)

- standart deviation

<br>

<code>
    sqrt(mean(abs(x - x.mean())** 2))
</code>

In [ ]:
np.std(v1)

- min / max value

In [ ]:
print(f'Min: {np.amin(v2)}')
print(f'Max: {np.amax(v2)}')