# Aufgabensammlung - Data Analysis mit Python - NumPy

#### 1. Importieren Sie das NumPy Package unter dem Namen 'np'

In [2]:
import numpy as np

#### 2. Stellen Sie sicher, dass die aktuelle Version von NumPy installiert ist.

In [3]:
np.__version__ 

'1.19.5'

#### 3. Erzeugen Sie einen Nullvektor der Größe 10.

In [5]:
np.zeros(shape=(10), dtype=np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. Erzeugen Sie einen Nullvektor der Größe 10, wobei das fünfte Element 3 ist.

In [12]:
a = np.zeros(shape=(10), dtype=np.int32)
a[4] = 3
a

array([0, 0, 0, 0, 3, 0, 0, 0, 0, 0])

#### 5. Erzeugen Sie einen Vektor, mit Werten zwischen 20 bis 50.

In [8]:
np.full(shape=(31), fill_value=range(20, 51))

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

#### 6. Erzeugen Sie einen Reverse-Vektor (Aus dem ersten Element wird das letzte Element)

In [16]:
np.array([1,2,3])[::-1]

array([3, 2, 1])

#### 7. Erzeugen Sie eine 3x3 Matrix mit den Elementen 0 bis 8.

In [17]:
np.random.randint(0, 8, size=(3,3))

array([[4, 5, 4],
       [5, 4, 0],
       [5, 2, 3]])

#### 8. Finden Sie Elemente im Array, die nicht Null sind.

In [22]:
np.array([0,1,2,3]) != 0 

array([False,  True,  True,  True])

#### 9. Erstellen Sie eine Einheitsmatrix.

#### 10. Erstellen Sie ein 3x3x3 Array mit zufälligen Werten.

In [25]:
np.random.random(size=(3,3,3))

array([[[0.70566123, 0.50370332, 0.50498429],
        [0.76078294, 0.40687169, 0.1176654 ],
        [0.81589305, 0.64015491, 0.9688105 ]],

       [[0.05184976, 0.32629864, 0.41706545],
        [0.42565236, 0.65562811, 0.13399298],
        [0.83250187, 0.95798489, 0.83074839]],

       [[0.3214113 , 0.2193832 , 0.8906812 ],
        [0.32876219, 0.25679611, 0.55611208],
        [0.05513673, 0.73880101, 0.14602806]]])

#### 10. Erstellen Sie ein 10x10 Array mit zufälligen Werten. Finden Sie das Minimum und Maximum.

In [27]:
a1 = np.random.random(size=(10,10))
print(f'Min: {np.amin(a1)}')
print(f'Max: {np.amax(a1)}')

Min: 0.019529303812496845
Max: 0.9942347281050212


#### 11. Erstellen Sie ein Vektor der Größe 20 mit zufälligen Werten und berechnen Sie den Mittelwert.

In [28]:
np.average(np.random.random(size=20))

0.5048915720594289

#### 12. Erstellen Sie ein Eindimensionales Array mit der Größe 15. Die Werte zwischen 5 und 10 sollen hierbei negativ sein.

[5]

#### 13. Wie können zwischen zwei Arrays gemeinsame Werte gefunden werden?

In [34]:
np.array_equal(np.array([1,2,3]), np.array([0,1,3]))

False

#### 14. Ermitteln Sie das Datum von gestern, heute und morgen. Nutzen Sie hierzu NumPy Funktionen.

nt.times_result(user=1.578125, system=0.609375, children_user=0.0, children_system=0.0, elapsed=0.0)


#### 15. Erstellen Sie ein Array mit Daten (=Plural Datum) des Monats August 2021. Verwenden Sie hierzu den Datentyp des Datumsformat.

#### 16. Ermitteln Sie nur den Integer-Teil einer Zahl mit Hilfe eines Random-Arrays.  Nutzen Sie hierzu 5 verschiedene Methoden zur Extraktion.

#### 17. Wie wird ein float Array in ein integer Array konvertiert? 

#### 18.  Erstellen Sie ein Array 'y' des Shapes (3,4). Das Array soll folgende Werte enthalten [2  7 12  0 3  9  3  4 4  0  1  3]

#### 19.  Wie lautet das Shape des in Aufgabe 18 erstellten Arrays 'y'? Verwenden Sie hierzu eine vordefinierte Funktion.

 #### 20. Wie lautet die Dimension des in Aufgabe 18 erstellten Arrays 'y'? Verwenden Sie hierzu eine vordefinierte Funktion.

#### 21.  Welche Länge hat das in Aufgabe 18 erstellte Array 'y'? Verwenden Sie hierzu eine vordefinierte Funktion.

#### 22.  Erstellen Sie eine 4x4 Einheitsmatrix.

#### 22.  Erstellen Sie eine 4x4 Nullmatrix.

#### 23.1 Erstellen Sie ein Array x mit 100 gleichverteilten Werten zwischen 0 and 2 * pi. Recherchieren Sie die hierzu benötigte Funktion.

#### 23.2 Erstellen Sie ein Array y, welches den Cosinus von x enthält  -    y[i] = cos(x[i])    -   (Hinweis: np.lookfor('cosine')).

#### 23.3 Plotten Sie x gegen y. Verwenden Sie hierzu https://matplotlib.org/

#### 24. Erstellen Sie ein Array 'y' des Shapes (3,4). Das Array soll folgende Werte enthalten [2 7 12 0 3 9 3 4 4 0 1 3]

#### 24.1 Geben Sie die erste Zeile aus.

#### 24.2 Geben Sie die zweite Spalte aus.

#### 24.3 Geben Sie das erste Element der dritten Spalte aus.

#### 24.4 Multiplizieren Sie jedes Element mit der Zahl PI.

#### 24.5 Multiplizieren Sie nur jedes zweite Element mit der Zahl Pi.


#### 24.6 Multiplizieren Sie jedes Element, welches größer als 5 ist mit der Zahl Pi und speichern Sie es in der Variable y_pi.

#### 24.7 Ersetzen Sie die Elemente der Wertigkeit 0 mit NaN. Alle anderen Elemente nehmen den Wert 1 an.

#### 24.8 Multiplizieren Sie das Array 'y' mit dem Array 'y_pi'. 

#### 25. Wie wird das untenstehende Verfahren 'A * 3' genannt?

In [ ]:
b = np.array([1, 2, 3])
erg = b * 3
print(erg)

#### 26. Multiplizieren Sie die Arrays 'b' und 'y_pi'. Was fällt Ihnen auf? Erläutern Sie.

#### 27. Wie können Sie den ValueError in Aufgabe 26 beheben? Verdeutlichen Sie sich das angewandte Verfahren in Aufgabe 25 und wenden Sie dieses so an, das die Arrays 'b' und 'y_pi' multipliziert werden können. Definieren Sie das neue Array mit 'y_pi_re_b'.

#### 28. Geben Sie alle Werte des 'y_pi_re_b aus, welche != 0 sind. Hierbei soll eine Matrix nur mit Wahrheitswerten erstellt werden.

#### 29. Wie viele Werte nicht 0 ? 

#### 30. Geben Sie nur die Elemente aus, bei denen ein True in der Matrix enthalten ist.  [Hinweis: np.where()]