# NumPy

In [2]:
import numpy as np

1. array with 8x4x4 dimensions

In [3]:
matrix1 = np.zeros((8,4,4))

2. change data type to integer

In [4]:
matrix1.dtype
matrix1 = np.zeros(shape=(8,4,4), dtype=np.int32)
matrix1.dtype

dtype('int32')

3. create an one dimensional array

In [5]:
cars = ['audi', 'bmw', 'vw']
cars_array = np.array(cars)
cars_array

array(['audi', 'bmw', 'vw'], dtype='<U4')

4. create multi-dimensional array with 3 dimensions

In [6]:
grades = [[[1,2,3,4,5,6], [1,2,3,4,5,6]],[[1,2,3,4,5,6], [1,2,3,4,5,6]]]
np.array(grades)

array([[[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]],

       [[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]]])

5. shape + ndim of array cars

In [7]:
cars_array.shape, cars_array.ndim

((3,), 1)

6. one-dimensional ndarray

In [8]:
np.ndarray((2))

array([ 5.62352797e-191, -1.48398091e+253])

7. two-dimensional ndarray

In [9]:
np.ndarray((2,2))

array([[ 2.12199579e-314,  4.22786102e-307],
       [ 4.09086355e-321, -2.82446473e+156]])

8. three-dimenaional ndarray

In [10]:
np.ndarray((2,2,2))
array_reshape = np.array([1,2,3,4,5,6,7,8,9])

array_reshape.reshape((1,3,3))

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

9. convert list to multi-dimensional array

In [11]:
list1 = ['item1', 'item2', 'item3']
np.asarray(list1)

array(['item1', 'item2', 'item3'], dtype='<U5')

10. generate a 2x4 array with random integers from 0 to 4

In [12]:
# array_randint = np.full((2,4), fill_value=np.random.randint(0,4), dtype=int)
array_randint = np.random.randint(5, size=(2,4))
array_randint

array([[0, 4, 1, 1],
       [0, 3, 0, 0]])

11. change the array's dimensions to 4x2

In [13]:
array_randint.reshape(4,2)

array([[0, 4],
       [1, 1],
       [0, 3],
       [0, 0]])

>transpose is the preferred method

In [14]:
np.transpose(array_randint)

array([[0, 0],
       [4, 3],
       [1, 0],
       [1, 0]])

#### help functions

<code>
    help(np.array)
    np.info(np.array)
</code>

## NumPy arithmetic operations 

In [15]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

- multiplication

In [16]:
v1 * v2, v1 * 2.5

(array([ 4, 10, 18]), array([2.5, 5. , 7.5]))

- division 

In [17]:
v1 / v2, v1 / 2

(array([0.25, 0.4 , 0.5 ]), array([0.5, 1. , 1.5]))

- addition / multiplication

In [18]:
print(f'Add: {v1 + v2}')
print(f'Sub: {v1 - v2}')

Add: [5 7 9]
Sub: [-3 -3 -3]


- raise to power

In [19]:
v2 ** 2

array([16, 25, 36], dtype=int32)

- square root

In [20]:
v2 ** 0.5, np.sqrt(v2)

(array([2.        , 2.23606798, 2.44948974]),
 array([2.        , 2.23606798, 2.44948974]))

## NumPy descriptive statistics

- sum

In [21]:
np.sum(v2, dtype=np.int32) # default: float64

15

- average

In [22]:
np.average(v2)

5.0

- standart deviation

<br>

<code>
    sqrt(mean(abs(x - x.mean())** 2))
</code>

In [23]:
np.std(v1)

0.816496580927726

- min / max value

In [24]:
print(f'Min: {np.amin(v2)}')
print(f'Max: {np.amax(v2)}')

Min: 4
Max: 6
